# Generated by Django 3.1.7 on 2021-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
