# Generated by Django 3.1.7 on 2021-04-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_auto_20210430_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='resumen',
            new_name='sinopsis',
        ),
    ]
