# Generated by Django 3.1.7 on 2021-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_auto_20210430_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='categoria',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Catástrofe', 'Catástrofe'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Documental', 'Documental'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Terror', 'Terror'), ('Infantil', 'Infantil')], default='Acción', max_length=30),
        ),
    ]
