# Generated by Django 3.1.7 on 2021-05-05 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_auto_20210505_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='peliculas', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
