# Generated by Django 3.1.7 on 2021-05-06 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_pelicula_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='directores', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
