# Generated by Django 3.1.7 on 2021-05-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_director_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'director', 'verbose_name_plural': 'directores'},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'verbose_name': 'pelicula', 'verbose_name_plural': 'peliculas'},
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='actores', verbose_name='Imagen')),
                ('peliculas', models.ManyToManyField(to='peliculas.Pelicula')),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actores',
                'ordering': ['-fecha_nacimiento'],
            },
        ),
    ]
