# Generated by Django 3.1.7 on 2021-05-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_auto_20210507_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['fecha_nacimiento'], 'verbose_name': 'director', 'verbose_name_plural': 'directores'},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['fecha_publicacion'], 'verbose_name': 'pelicula', 'verbose_name_plural': 'peliculas'},
        ),
    ]
