# Generated by Django 3.1.7 on 2021-05-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0011_auto_20210511_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='valoracion',
            field=models.IntegerField(choices=[(1, 'Muy mala'), (2, 'Mala'), (3, 'Normal'), (4, 'Buena'), (5, 'Muy Buena')], default=2),
        ),
    ]
