# Generated by Django 3.1.7 on 2021-05-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0012_pelicula_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='numVotos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='valoracionMedia',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='valoracionTotal',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='valoracion',
            field=models.DecimalField(choices=[(0.0, 0), (1.0, 1), (2.0, 2), (3.0, 3), (4.0, 4), (5.0, 5)], decimal_places=1, default=0.0, max_digits=1),
        ),
    ]
