# Generated by Django 3.1.7 on 2021-05-13 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0015_auto_20210512_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(default=90, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='pais',
            field=models.CharField(choices=[('AD', 'Andorra'), ('AE', 'Emiratos Árabes Unidos'), ('AR', 'Argentina'), ('AT', 'Austria'), ('AU', 'Australia'), ('BE', 'Bélgica'), ('BR', 'Brasil'), ('CA', 'Canadá'), ('CH', 'Suiza'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('CU', 'Cuba'), ('DE', 'Alemania'), ('EG', 'Egipto'), ('ES', 'España'), ('FI', 'Finlandia'), ('FR', 'Francia'), ('GR', 'Grecia'), ('HK', 'Hong Kong'), ('ID', 'Indonesia'), ('IN', 'India'), ('IR', 'Irán'), ('IT', 'Italia'), ('JP', 'Japón'), ('KR', 'Corea del Sur'), ('MX', 'México'), ('MY', 'Malsia'), ('NG', 'Nigeria'), ('NL', 'Países Bajos'), ('PL', 'Polonia'), ('PT', 'Portugal'), ('RU', 'Rusia'), ('SA', 'Arabia Saudí'), ('SG', 'Singapur'), ('TR', 'Turquía'), ('TW', 'Taiwán'), ('UK', 'Reino Unido'), ('UA', 'Ucrania'), ('US', 'Estados Unidos')], max_length=70, null=True),
        ),
    ]
