# Generated by Django 3.1.7 on 2021-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0017_auto_20210513_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='pais',
            field=models.CharField(choices=[('Andorra', 'Andorra'), ('Emiratos Árabes Unidos', 'Emiratos Árabes Unidos'), ('Argentina', 'Argentina'), ('Austria', 'Austria'), ('Australia', 'Australia'), ('Bélgica', 'Bélgica'), ('Brasil', 'Brasil'), ('Canadá', 'Canadá'), ('Suiza', 'Suiza'), ('Suiza', 'Suiza'), ('China', 'China'), ('Colombia', 'Colombia'), ('Cuba', 'Cuba'), ('Alemania', 'Alemania'), ('Egipto', 'Egipto'), ('España', 'España'), ('Finlandia', 'Finlandia'), ('Francia', 'Francia'), ('Grecia', 'Grecia'), ('Hong Kong', 'Hong Kong'), ('Indonesia', 'Indonesia'), ('India', 'India'), ('Irán', 'Irán'), ('Italia', 'Italia'), ('Japón', 'Japón'), ('Corea del Sur', 'Corea del Sur'), ('México', 'México'), ('Malsia', 'Malsia'), ('Nigeria', 'Nigeria'), ('Países Bajos', 'Países Bajos'), ('Polonia', 'Polonia'), ('Portugal', 'Portugal'), ('Rusia', 'Rusia'), ('Arabia Saudí', 'Arabia Saudí'), ('Singapur', 'Singapur'), ('Turquía', 'Turquía'), ('Taiwán', 'Taiwán'), ('Reino Unido', 'Reino Unido'), ('Ucrania', 'Ucrania'), ('Estados Unidos', 'Estados Unidos')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='pais',
            field=models.CharField(choices=[('Andorra', 'Andorra'), ('Emiratos Árabes Unidos', 'Emiratos Árabes Unidos'), ('Argentina', 'Argentina'), ('Austria', 'Austria'), ('Australia', 'Australia'), ('Bélgica', 'Bélgica'), ('Brasil', 'Brasil'), ('Canadá', 'Canadá'), ('Suiza', 'Suiza'), ('Suiza', 'Suiza'), ('China', 'China'), ('Colombia', 'Colombia'), ('Cuba', 'Cuba'), ('Alemania', 'Alemania'), ('Egipto', 'Egipto'), ('España', 'España'), ('Finlandia', 'Finlandia'), ('Francia', 'Francia'), ('Grecia', 'Grecia'), ('Hong Kong', 'Hong Kong'), ('Indonesia', 'Indonesia'), ('India', 'India'), ('Irán', 'Irán'), ('Italia', 'Italia'), ('Japón', 'Japón'), ('Corea del Sur', 'Corea del Sur'), ('México', 'México'), ('Malsia', 'Malsia'), ('Nigeria', 'Nigeria'), ('Países Bajos', 'Países Bajos'), ('Polonia', 'Polonia'), ('Portugal', 'Portugal'), ('Rusia', 'Rusia'), ('Arabia Saudí', 'Arabia Saudí'), ('Singapur', 'Singapur'), ('Turquía', 'Turquía'), ('Taiwán', 'Taiwán'), ('Reino Unido', 'Reino Unido'), ('Ucrania', 'Ucrania'), ('Estados Unidos', 'Estados Unidos')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='trailer',
            field=models.URLField(max_length=300),
        ),
    ]
