# Generated by Django 3.1.7 on 2021-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0018_auto_20210513_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='pais',
            field=models.CharField(blank=True, choices=[('Alemania', 'Alemania'), ('Andorra', 'Andorra'), ('Arabia Saudí', 'Arabia Saudí'), ('Argentina', 'Argentina'), ('Austria', 'Austria'), ('Australia', 'Australia'), ('Bélgica', 'Bélgica'), ('Brasil', 'Brasil'), ('Canadá', 'Canadá'), ('China', 'China'), ('Colombia', 'Colombia'), ('Corea del Sur', 'Corea del Sur'), ('Cuba', 'Cuba'), ('Egipto', 'Egipto'), ('Emiratos Árabes Unidos', 'Emiratos Árabes Unidos'), ('España', 'España'), ('Estados Unidos', 'Estados Unidos'), ('Finlandia', 'Finlandia'), ('Francia', 'Francia'), ('Grecia', 'Grecia'), ('Hong Kong', 'Hong Kong'), ('Indonesia', 'Indonesia'), ('India', 'India'), ('Irán', 'Irán'), ('Italia', 'Italia'), ('Japón', 'Japón'), ('México', 'México'), ('Malsia', 'Malsia'), ('Nigeria', 'Nigeria'), ('Países Bajos', 'Países Bajos'), ('Polonia', 'Polonia'), ('Portugal', 'Portugal'), ('Reino Unido', 'Reino Unido'), ('Rusia', 'Rusia'), ('Singapur', 'Singapur'), ('Suiza', 'Suiza'), ('Taiwán', 'Taiwán'), ('Turquía', 'Turquía'), ('Ucrania', 'Ucrania')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='pais',
            field=models.CharField(blank=True, choices=[('Alemania', 'Alemania'), ('Andorra', 'Andorra'), ('Arabia Saudí', 'Arabia Saudí'), ('Argentina', 'Argentina'), ('Austria', 'Austria'), ('Australia', 'Australia'), ('Bélgica', 'Bélgica'), ('Brasil', 'Brasil'), ('Canadá', 'Canadá'), ('China', 'China'), ('Colombia', 'Colombia'), ('Corea del Sur', 'Corea del Sur'), ('Cuba', 'Cuba'), ('Egipto', 'Egipto'), ('Emiratos Árabes Unidos', 'Emiratos Árabes Unidos'), ('España', 'España'), ('Estados Unidos', 'Estados Unidos'), ('Finlandia', 'Finlandia'), ('Francia', 'Francia'), ('Grecia', 'Grecia'), ('Hong Kong', 'Hong Kong'), ('Indonesia', 'Indonesia'), ('India', 'India'), ('Irán', 'Irán'), ('Italia', 'Italia'), ('Japón', 'Japón'), ('México', 'México'), ('Malsia', 'Malsia'), ('Nigeria', 'Nigeria'), ('Países Bajos', 'Países Bajos'), ('Polonia', 'Polonia'), ('Portugal', 'Portugal'), ('Reino Unido', 'Reino Unido'), ('Rusia', 'Rusia'), ('Singapur', 'Singapur'), ('Suiza', 'Suiza'), ('Taiwán', 'Taiwán'), ('Turquía', 'Turquía'), ('Ucrania', 'Ucrania')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='pais',
            field=models.CharField(blank=True, choices=[('Alemania', 'Alemania'), ('Andorra', 'Andorra'), ('Arabia Saudí', 'Arabia Saudí'), ('Argentina', 'Argentina'), ('Austria', 'Austria'), ('Australia', 'Australia'), ('Bélgica', 'Bélgica'), ('Brasil', 'Brasil'), ('Canadá', 'Canadá'), ('China', 'China'), ('Colombia', 'Colombia'), ('Corea del Sur', 'Corea del Sur'), ('Cuba', 'Cuba'), ('Egipto', 'Egipto'), ('Emiratos Árabes Unidos', 'Emiratos Árabes Unidos'), ('España', 'España'), ('Estados Unidos', 'Estados Unidos'), ('Finlandia', 'Finlandia'), ('Francia', 'Francia'), ('Grecia', 'Grecia'), ('Hong Kong', 'Hong Kong'), ('Indonesia', 'Indonesia'), ('India', 'India'), ('Irán', 'Irán'), ('Italia', 'Italia'), ('Japón', 'Japón'), ('México', 'México'), ('Malsia', 'Malsia'), ('Nigeria', 'Nigeria'), ('Países Bajos', 'Países Bajos'), ('Polonia', 'Polonia'), ('Portugal', 'Portugal'), ('Reino Unido', 'Reino Unido'), ('Rusia', 'Rusia'), ('Singapur', 'Singapur'), ('Suiza', 'Suiza'), ('Taiwán', 'Taiwán'), ('Turquía', 'Turquía'), ('Ucrania', 'Ucrania')], max_length=70, null=True),
        ),
    ]
