# Generated by Django 3.1.7 on 2021-05-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0020_auto_20210518_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='voto_usuarios',
        ),
        migrations.DeleteModel(
            name='UsuarioVoto',
        ),
    ]
