# Generated by Django 3.1.7 on 2021-05-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0022_auto_20210519_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(null=True, related_name='actores', to='peliculas.Actor'),
        ),
    ]
