# Generated by Django 3.1.7 on 2021-05-19 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0024_auto_20210519_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='valoracionTotal',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='voto_usuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='valoracion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='valoracion',
            field=models.DecimalField(choices=[(0.0, 0), (1.0, 1), (2.0, 2), (3.0, 3), (4.0, 4), (5.0, 5), (6.0, 6), (7.0, 7), (8.0, 8), (9.0, 9), (10.0, 10)], decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.DeleteModel(
            name='Voto',
        ),
    ]
