# Generated by Django 3.1.7 on 2021-06-09 09:25

from django.db import migrations, models
import peliculas.models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0026_auto_20210519_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=peliculas.models.Pelicula.generarRutaImagen, verbose_name='Imagen'),
        ),
    ]
