# Generated by Django 3.1.7 on 2021-06-11 08:08

from django.db import migrations, models
import peliculas.models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0027_auto_20210609_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=peliculas.models.Actor.generarRutaImagen, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='director',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=peliculas.models.Director.generarRutaImagen, verbose_name='Imagen'),
        ),
    ]
